version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    #automatically update files.
    volumes:
      - ./app:/app
    command: >
<<<<<<< HEAD
      sh -c "python manage.py wait_for_db && 
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
=======
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME-app
>>>>>>> 10442a0a11640d94a97911ab2a442feeab7f5c4f
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
<<<<<<< HEAD

=======
>>>>>>> 10442a0a11640d94a97911ab2a442feeab7f5c4f
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
<<<<<<< HEAD
          
=======
>>>>>>> 10442a0a11640d94a97911ab2a442feeab7f5c4f
